min_table_num: 0
max_table_size: 12
min_table_size: 2
sun_link: "https://sun-asterisk.vn"
img_logo: "logo.png"
contact_link: "info@junkyburget.com"
footer_logo_link: "footer_logo.png"
img_stamp: "stamp.png"
bs3_css: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
awesome_font: "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"
jquery_1: "http://code.jquery.com/jquery-1.12.1.min.js"
bs3_js: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
dtb_css: "https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap.min.css"
dtb_js: "https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"
dtb_bs_js: "https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap.min.js"
img_chicken: "chicken.png"
caro_img: "small_slider_bg.jpg"
caro_big_img: "large_slider_img.jpg"
min_table_number: 1
max_table_size: 12
min_table_size: 2
icon_table: "table-icon.png"
pagenate_tables: 9
reservation_icon: "reservation-icon.png"
min_book_size: 1
img_book_frame: "book-frame.png"
pagenate_orders: 8
paid_img: "paid.png"
